"""empty message

Revision ID: 1cf9f0a82a21
Revises: 45faa64d809c
Create Date: 2023-09-06 17:51:02.516600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf9f0a82a21'
down_revision = '45faa64d809c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('published_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('published_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
