"""empty message

Revision ID: 20ae5aa78fbd
Revises: bdb1f1c922d5
Create Date: 2023-08-26 22:57:28.080138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ae5aa78fbd'
down_revision = 'bdb1f1c922d5'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('transactions', schema=None) as batch_op:
#         batch_op.alter_column('status',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Enum('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
#                existing_nullable=False)

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('transactions', schema=None) as batch_op:
#         batch_op.alter_column('status',
#                existing_type=sa.Enum('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
#                type_=sa.VARCHAR(),
#                existing_nullable=False)

#     # ### end Alembic commands ###


def upgrade():
    op.execute("CREATE TYPE transaction_status_enum AS ENUM ('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error')")

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
               existing_nullable=False,
               postgresql_using="status::transaction_status_enum")

def downgrade():
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="status::VARCHAR")

    op.execute("DROP TYPE transaction_status_enum")
