"""empty message

Revision ID: 3025b076eeb5
Revises: e30efdbbd54e
Create Date: 2023-08-30 14:27:30.566562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3025b076eeb5'
down_revision = 'e30efdbbd54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_categories', schema=None) as batch_op:
        batch_op.drop_constraint('book_categories_book_id_key', type_='unique')
        batch_op.drop_constraint('book_categories_category_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('book_categories_category_id_key', ['category_id'])
        batch_op.create_unique_constraint('book_categories_book_id_key', ['book_id'])

    # ### end Alembic commands ###
