"""empty message

Revision ID: 37692818f8c5
Revises: 81d8808c71b3
Create Date: 2023-08-30 13:53:30.991687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37692818f8c5'
down_revision = '81d8808c71b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_address_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('user_address_id_key', ['address_id'])

    # ### end Alembic commands ###
