"""empty message

Revision ID: 45faa64d809c
Revises: d5d926089dfc
Create Date: 2023-09-06 17:49:59.486300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45faa64d809c'
down_revision = 'd5d926089dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('category2')
        batch_op.drop_column('category1')

    # ### end Alembic commands ###
