"""empty message

Revision ID: 7ec2122192de
Revises: 87aaef6775b1
Create Date: 2023-08-30 14:07:46.952978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec2122192de'
down_revision = '87aaef6775b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_listings', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('favorite_listings_listing_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'])

    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorite_listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favorite_listings_listing_id_key', ['listing_id'])
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
