"""empty message

Revision ID: 8797ac764bb0
Revises: da02dfaac9c6
Create Date: 2023-09-21 12:13:37.276747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8797ac764bb0'
down_revision = 'da02dfaac9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               nullable=True)

    with op.batch_alter_table('favorite_listings', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('listing_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('favorite_counter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sale_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Activo', 'Reservado', 'Vendido', 'Cancelado', name='status_enum'),
               nullable=True)
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('punctuation',
               existing_type=postgresql.ENUM('1', '2', '3', '4', '5', name='punctuation_enum'),
               nullable=True)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
               nullable=True)
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('document_type',
               existing_type=postgresql.ENUM('DNI', 'NIE', 'Passport', name='document_type_enum'),
               nullable=True)
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('document_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('document_type',
               existing_type=postgresql.ENUM('DNI', 'NIE', 'Passport', name='document_type_enum'),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Completada', 'Cancelada', 'Suspendida', 'Procesando', 'Error', name='transaction_status_enum'),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('punctuation',
               existing_type=postgresql.ENUM('1', '2', '3', '4', '5', name='punctuation_enum'),
               nullable=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Activo', 'Reservado', 'Vendido', 'Cancelado', name='status_enum'),
               nullable=False)
        batch_op.alter_column('sale_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('favorite_counter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('listing_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorite_listings', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
