"""empty message

Revision ID: 87aaef6775b1
Revises: 37692818f8c5
Create Date: 2023-08-30 13:57:46.897069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aaef6775b1'
down_revision = '37692818f8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_user_followed_id_key', type_='unique')
        batch_op.drop_constraint('favorite_user_follower_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favorite_user_follower_id_key', ['follower_id'])
        batch_op.create_unique_constraint('favorite_user_followed_id_key', ['followed_id'])

    # ### end Alembic commands ###
