"""empty message

Revision ID: 97c31863639c
Revises: 7ec2122192de
Create Date: 2023-08-30 14:13:02.155680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c31863639c'
down_revision = '7ec2122192de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_receiver_id_key', type_='unique')
        batch_op.drop_constraint('reviews_reviewer_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('reviews_reviewer_id_key', ['reviewer_id'])
        batch_op.create_unique_constraint('reviews_receiver_id_key', ['receiver_id'])

    # ### end Alembic commands ###
