"""empty message

Revision ID: a5eb893ae039
Revises: 1cb8c9b42b40
Create Date: 2023-09-04 17:05:12.184424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb893ae039'
down_revision = '1cb8c9b42b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint('album_listing_id_key', type_='unique')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('album_listing_id_key', ['listing_id'])

    # ### end Alembic commands ###
