"""empty message

Revision ID: bdb1f1c922d5
Revises: 99ce500c3445
Create Date: 2023-08-26 22:46:09.584718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdb1f1c922d5'
down_revision = '99ce500c3445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('listing_title', sa.String(length=200), nullable=False),
    sa.Column('favorite_counter', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('Activo', 'Reservado', 'Vendido', 'Cancelado', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id'),
    sa.UniqueConstraint('book_id'),
    sa.UniqueConstraint('seller_id')
    )
    op.drop_table('lintings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lintings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('favorite_counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lintings_pkey'),
    sa.UniqueConstraint('album_id', name='lintings_album_id_key'),
    sa.UniqueConstraint('book_id', name='lintings_book_id_key'),
    sa.UniqueConstraint('seller_id', name='lintings_seller_id_key')
    )
    op.drop_table('listings')
    # ### end Alembic commands ###
