"""empty message

Revision ID: da02dfaac9c6
Revises: 620c634edaf5
Create Date: 2023-09-20 17:09:06.452158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da02dfaac9c6'
down_revision = '620c634edaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('flat_number',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('flat_number',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
