"""empty message

Revision ID: e30efdbbd54e
Revises: 97c31863639c
Create Date: 2023-08-30 14:20:44.646514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30efdbbd54e'
down_revision = '97c31863639c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('listings_album_id_key', type_='unique')
        batch_op.drop_constraint('listings_book_id_key', type_='unique')
        batch_op.drop_constraint('listings_seller_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'album', ['album_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('listings_seller_id_key', ['seller_id'])
        batch_op.create_unique_constraint('listings_book_id_key', ['book_id'])
        batch_op.create_unique_constraint('listings_album_id_key', ['album_id'])
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
