"""empty message

Revision ID: ef5a2f24ce88
Revises: 68e154ce3488
Create Date: 2023-08-31 07:23:33.424618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5a2f24ce88'
down_revision = '68e154ce3488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('address_city_key', type_='unique')
        batch_op.drop_constraint('address_flat_number_key', type_='unique')
        batch_op.drop_constraint('address_state_key', type_='unique')
        batch_op.drop_constraint('address_zip_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_unique_constraint('address_zip_code_key', ['zip_code'])
        batch_op.create_unique_constraint('address_state_key', ['state'])
        batch_op.create_unique_constraint('address_flat_number_key', ['flat_number'])
        batch_op.create_unique_constraint('address_city_key', ['city'])

    # ### end Alembic commands ###
